# Generated by Django 4.2.5 on 2023-10-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_resource_topic_delete_videoresource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('video', 'Video'), ('website', 'Website'), ('books', 'Books')], default='website', max_length=20),
        ),
    ]
